
name: test-action-alt-coverage

on:
  push:
  release:
    types: published

jobs:

  run-tests:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v1


      - name: use this action, with existing code coverage results
        id: testAction3
        uses: ./
        with:
          coverage_results_path: jacoco-report/example.jacoco.xml
          coverage_report_name: Jacoco-code-coverage
          coverage_report_title: Jacco code coverage
          github_token: ${{ secrets.GITHUB_TOKEN }}
